import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-surface': '#213145',
        'secondary': '#006e1c',
        'on-primary': '#ffffff',
        'secondary-fixed-dim': '#78dc77',
        'surface-dim': '#cbdbf5',
        'on-tertiary-fixed': '#111c2d',
        'error': '#ba1a1a',
        'on-primary-fixed-variant': '#544600',
        'tertiary-fixed-dim': '#bcc7de',
        'surface-variant': '#d3e4fe',
        'background': '#f8f9ff',
        'secondary-container': '#91f78e',
        'secondary-fixed': '#94f990',
        'on-error': '#ffffff',
        'on-surface': '#0b1c30',
        'on-primary-container': '#705e00',
        'on-secondary-fixed-variant': '#005313',
        'on-secondary-fixed': '#002204',
        'surface-container': '#e5eeff',
        'outline': '#6b7385',
        'on-error-container': '#93000a',
        'surface-tint': '#705d00',
        'primary': '#705d00',
        'inverse-primary': '#e9c400',
        'outline-variant': '#ccd3e1',
        'inverse-on-surface': '#eaf1ff',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#f8f9ff',
        'on-secondary': '#ffffff',
        'tertiary-container': '#cfdaf2',
        'on-primary-fixed': '#221b00',
        'on-tertiary-container': '#545f74',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#d8e3fb',
        'surface-container-low': '#eff4ff',
        'on-surface-variant': '#46506a',
        'tertiary': '#545f73',
        'primary-fixed-dim': '#e9c400',
        'on-background': '#0b1c30',
        'surface-container-highest': '#d3e4fe',
        'primary-fixed': '#ffe16d',
        'on-tertiary-fixed-variant': '#3c475a',
        'primary-container': '#ffd700',
        'error-container': '#ffdad6',
        'surface': '#f8f9ff',
        'surface-container-high': '#dce9ff',
        'on-secondary-container': '#00731e',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        'margin-desktop': '40px',
        gutter: '24px',
        'container-max': '1280px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'label-md': ['Inter'],
        'headline-md': ['Montserrat'],
        'label-sm': ['Inter'],
        'body-sm': ['Inter'],
        'body-md': ['Inter'],
        'body-lg': ['Inter'],
        'headline-lg': ['Montserrat'],
        'headline-lg-mobile': ['Montserrat'],
        'headline-xl': ['Montserrat'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [forms, containerQueries],
}
